package com.example.myapplication.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue

data class AppStrings(
    val appName: String,
    val home: String,
    val messages: String,
    val myAccount: String,
    val settings: String,
    val profile: String,
    val network: String,
    val myMentor: String,
    val findMentor: String,
    val findProjectPartner: String,
    val safeMessage: String,
    val events: String,
    val save: String,
    val back: String,
    val edit: String,
    val name: String,
    val surname: String,
    val tcNo: String,
    val education: String,
    val university: String,
    val department: String,
    val interests: String,
    val learnGoals: String,
    val goals: String,
    val weeklyTime: String,
    val successPoints: String,
    val documents: String,
    val appSettings: String,
    val darkMode: String,
    val accessibilityMode: String,
    val language: String,
    val notifications: String,
    val examMode: String,
    val clearCache: String,
    val dataSaver: String,
    val kvkk: String,
    val externalAccounts: String,
    val analyzeInterests: String,
    val findingMentor: String,
    val aiMatching: String
)

val trStrings = AppStrings(
    appName = "MENTORNET",
    home = "Hub",
    messages = "Mesaj",
    myAccount = "Hesabım",
    settings = "AYARLAR",
    profile = "Profil",
    network = "Network",
    myMentor = "Mentörüm",
    findMentor = "Uygun Mentörü / Arkadaşı Bul",
    findProjectPartner = "Proje Ortağı Bul",
    safeMessage = "Güvenli Mesaj",
    events = "Etkinlikler",
    save = "KAYDET",
    back = "Geri",
    edit = "Düzenle",
    name = "İsim",
    surname = "Soyisim",
    tcNo = "TC Kimlik No",
    education = "Eğitim Seviyesi",
    university = "Üniversite",
    department = "Bölüm",
    interests = "İlgi Alanları",
    learnGoals = "Öğrenmek İstedikleri",
    goals = "Gelecek Hedefleri",
    weeklyTime = "Haftalık Ayrılan Zaman (Saat)",
    successPoints = "Başarı Puanı",
    documents = "BELGELER VE DOĞRULAMA",
    appSettings = "UYGULAMA AYARLARI",
    darkMode = "Karanlık Mod",
    accessibilityMode = "Erişilebilir Mod (Engelsiz)",
    language = "Uygulama Dili",
    notifications = "Anlık Bildirimler",
    examMode = "Sınav / Yoğunluk Modu",
    clearCache = "Önbelleği Temizle",
    dataSaver = "Veri Tasarrufu Modu",
    kvkk = "KVKK Veri İzinleri",
    externalAccounts = "Harici Hesap Entegrasyonu",
    analyzeInterests = "AI ile kişisel ilgileriniz analiz ediliyor...",
    findingMentor = "Sizin için uygun mentör bulunuyor.",
    aiMatching = "AI Eşleştirme"
)

val enStrings = AppStrings(
    appName = "MENTORNET",
    home = "Hub",
    messages = "Messages",
    myAccount = "My Account",
    settings = "SETTINGS",
    profile = "Profile",
    network = "Network",
    myMentor = "My Mentor",
    findMentor = "Find Suitable Mentor / Friend",
    findProjectPartner = "Find Project Partner",
    safeMessage = "Safe Message",
    events = "Events",
    save = "SAVE",
    back = "Back",
    edit = "Edit",
    name = "Name",
    surname = "Surname",
    tcNo = "ID Number",
    education = "Education Level",
    university = "University",
    department = "Department",
    interests = "Interests",
    learnGoals = "What They Want to Learn",
    goals = "Future Goals",
    weeklyTime = "Weekly Time Allocated (Hours)",
    successPoints = "Success Points",
    documents = "DOCUMENTS AND VERIFICATION",
    appSettings = "APP SETTINGS",
    darkMode = "Dark Mode",
    accessibilityMode = "Accessibility Mode",
    language = "App Language",
    notifications = "Push Notifications",
    examMode = "Exam / Busy Mode",
    clearCache = "Clear Cache",
    dataSaver = "Data Saver Mode",
    kvkk = "KVKK Data Permissions",
    externalAccounts = "External Account Integration",
    analyzeInterests = "Analyzing your personal interests with AI...",
    findingMentor = "Finding a suitable mentor for you.",
    aiMatching = "AI Matching"
)

@Composable
fun getAppStrings(viewModel: MentorNetViewModel): AppStrings {
    val isEnglish by viewModel.isEnglish.collectAsState()
    return if (isEnglish) enStrings else trStrings
}
